"""
Build a NotebookLM-ready bundle for a scope (week folder or block folder).

Usage:
  python scripts/notebooklm_export.py <vault-relative-path>
    e.g. block-0-basecamp/week-01-basecamp-part-1-prompting-rags--basecamp-part-2-vibe-coding
    e.g. block-0-basecamp

For each .md lesson inside the scope:
  - strips YAML frontmatter
  - rewrites [[wikilinks]] to plain text (or a trailing "See: <title>" line)
  - writes a cleaned copy to <scope>/07-notebooklm-pack/<basename>.md
Also writes bundle.md concatenating all lessons and a README.md with
upload instructions.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VAULT = ROOT / "vault"

FRONTMATTER_RE = re.compile(r"^---\n.*?\n---\n", re.DOTALL)
WIKILINK_RE = re.compile(r"\[\[([^\]|]+?)(?:\|([^\]]+))?\]\]")


def clean(md: str) -> str:
    md = FRONTMATTER_RE.sub("", md, count=1)
    md = WIKILINK_RE.sub(lambda m: m.group(2) or m.group(1), md)
    return md.strip() + "\n"


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: notebooklm_export.py <vault-relative-path>")
        return 1
    scope = VAULT / sys.argv[1]
    if not scope.exists():
        print(f"Not found: {scope}")
        return 1

    pack_dir = scope / "07-notebooklm-pack"
    pack_dir.mkdir(parents=True, exist_ok=True)

    lessons = sorted(
        [
            p
            for p in scope.rglob("*.md")
            if "07-notebooklm-pack" not in p.parts and p.name != "_week.md"
        ]
    )

    bundle_parts: list[str] = []
    for f in lessons:
        cleaned = clean(f.read_text(encoding="utf-8"))
        out = pack_dir / f.name
        out.write_text(cleaned, encoding="utf-8")
        bundle_parts.append(f"# {f.stem}\n\n{cleaned}")

    (pack_dir / "bundle.md").write_text(
        "\n\n---\n\n".join(bundle_parts), encoding="utf-8"
    )
    (pack_dir / "README.md").write_text(
        "# NotebookLM pack\n\n"
        "1. Open <https://notebooklm.google.com>.\n"
        "2. Create a new notebook.\n"
        "3. Upload every `.md` in this folder (or just `bundle.md` for a single source).\n"
        "4. Generate: Audio Overview, Mind Map, FAQ, or Video Overview.\n\n"
        "This pack was generated by `scripts/notebooklm_export.py`. Re-run it whenever "
        "the source lessons change.\n",
        encoding="utf-8",
    )
    print(f"[ok] Wrote {len(lessons)} lessons + bundle.md to {pack_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
